image: Visual Studio 2017
clone_folder: c:\projects\darknet
cache: C:\Tools\vcpkg\installed\

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Cygwin64
      COMPILER: cygwin
      CYGWIN_NOWINPATH: yes
      CYGSH: C:\cygwin64\bin\bash -c
    - platform: Win64
      COMPILER: vs
      configuration: Release
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: yes
    - platform: Win64
      COMPILER: vs
      configuration: Debug
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: yes
    - platform: Win64
      COMPILER: vs
      configuration: Release
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: no
    - platform: Win64
      COMPILER: vs
      configuration: Debug
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: no
    - platform: Win64
      COMPILER: vs
      configuration: Release
      USE_INTEGRATED_LIBS: yes

install:
  - if [%COMPILER%]==[vs] cinst cmake ninja
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - if [%COMPILER%]==[vs] call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - if [%COMPILER%]==[cygwin] SET "PATH=C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\cygwin64\usr\bin;%PATH%"
  - if [%COMPILER%]==[cygwin] SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - git submodule -q update --init --recursive
  - cd %WORKSPACE%\
  - if [%USE_CUDA%]==[yes] curl -L https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe -o setup.exe
  - if [%USE_CUDA%]==[yes] .\setup.exe -s nvcc_10.1 cuobjdump_10.1 nvprune_10.1 cupti_10.1 gpu_library_advisor_10.1 memcheck_10.1 nvdisasm_10.1 nvprof_10.1 visual_profiler_10.1 visual_studio_integration_10.1 cublas_10.1 cublas_dev_10.1 cudart_10.1 cufft_10.1 cufft_dev_10.1 curand_10.1 curand_dev_10.1 cusolver_10.1 cusolver_dev_10.1 cusparse_10.1 cusparse_dev_10.1 nvgraph_10.1 nvgraph_dev_10.1 npp_10.1 npp_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 nvml_dev_10.1 occupancy_calculator_10.1 fortran_examples_10.1
  - if [%USE_CUDA%]==[yes] set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.1
  - if [%USE_CUDA%]==[yes] set CUDA_PATH_V10_1=%CUDA_PATH%
  - if [%USE_CUDA%]==[yes] set CUDA_TOOLKIT_ROOT_DIR=%CUDA_PATH%
  - if [%USE_CUDA%]==[yes] set PATH=%CUDA_PATH%\bin;%PATH%
  - cd %WORKSPACE%\
  - mkdir cygwin-downloads
  - ps: if($env:COMPILER -eq "cygwin") { Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile $env:WORKSPACE\cygwin-setup.exe }
  - if [%COMPILER%]==[cygwin] %WORKSPACE%\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --root C:\cygwin64 --local-package-dir %WORKSPACE%\cygwin-downloads --packages gcc-g++,cmake,libopencv-devel,libncurses-devel
  - ps: if($env:COMPILER -eq "cygwin") { Invoke-WebRequest https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0.tar.gz -OutFile $env:WORKSPACE\cmake-3.14.0.tar.gz }
  - if [%COMPILER%]==[cygwin] %CYGSH% 'tar zxvf cmake-3.14.0.tar.gz'
  - if [%COMPILER%]==[cygwin] cd %WORKSPACE%\cmake-3.14.0
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake .'
  - if [%COMPILER%]==[cygwin] %CYGSH% 'make -j8'
  - if [%COMPILER%]==[cygwin] %CYGSH% 'make install'
  - if [%COMPILER%]==[cygwin] cd %WORKSPACE%
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] cd %VCPKG_ROOT%
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] git pull
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] .\bootstrap-vcpkg.bat
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] if [%USE_CUDA%]==[yes] vcpkg install cuda
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] vcpkg install stb pthreads
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] vcpkg install opencv[ffmpeg] ## opencv[ffmpeg,cuda] is too big to build, timing out (>1h). We use plain openCV also for CUDA builds (toolchain can manage this strange situation anyway)
  - cd %WORKSPACE%\darknet\
  - mkdir build_debug && cd build_debug
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"'
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] if [%configuration%]==[Debug] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_BUILD_TYPE="Debug" ..
  - cd ..
  - mkdir build_release && cd build_release
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release"'
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] if [%configuration%]==[Release] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_BUILD_TYPE="Release" ..
  - if [%COMPILER%]==[vs] if     [%USE_INTEGRATED_LIBS%]==[yes] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" -DCMAKE_BUILD_TYPE="Release" ..
  - cd ..

build_script:
  - if [%COMPILER%]==[cygwin]                                                                   cd build_debug   && %CYGSH% 'cmake --build . --target install -- -j8'              && cd ..
  - if [%COMPILER%]==[cygwin]                                                                   cd build_release && %CYGSH% 'cmake --build . --target install -- -j8'              && cd ..
  - if [%COMPILER%]==[vs] if NOT [%USE_INTEGRATED_LIBS%]==[yes] if [%configuration%]==[Debug]   cd build_debug   && cmake --build . --config Debug --parallel 8 --target install   && cd ..
  - if [%COMPILER%]==[vs]                                       if [%configuration%]==[Release] cd build_release && cmake --build . --config Release --parallel 8 --target install && cd ..

artifacts:
  - path: lib
  - path: '*.exe'
